version: "3"
services:
  nginx:
    ports:
      - "4000:80"
  node-app-container:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run dev