version: "3"
services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "4000:80"
    volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app-container:
    build: .
    image: 42123674/node-docker
    # ports:
    #   - "4000:4000"
    depends_on:
      - mongo
      - nginx

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: usuario
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - mongo-db:/data/db


volumes:
  mongo-db: